# services:
#   - type: web
#     name: best-buddies-bolivia
#     env: php
#     buildCommand: |
#       composer install --no-dev --optimize-autoloader
#       npm install
#       npm run build
#       php artisan config:cache
#       php artisan route:cache
#       php artisan view:cache
#     startCommand: |
#       php artisan serve --host=0.0.0.0 --port=$PORT
#     envVars:
#       - key: APP_ENV
#         value: production
#       - key: APP_DEBUG
#         value: false
#       - key: LOG_CHANNEL
#         value: stderr

services:
  - type: web
    name: best-buddies-bolivia
    env: php
    buildCommand: |
      echo "=== Installing PHP dependencies ==="
      composer install --no-dev --optimize-autoloader
      echo "=== Installing Node.js dependencies ==="
      npm ci --only=production
      echo "=== Building assets ==="
      npm run build
      echo "=== Listing build files ==="
      ls -la public/build/ || echo "Build directory not found"
    startCommand: |
      php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: NODE_ENV
        value: production